### ISSUE TITLE
Create Liquibase scripts and Docker image for Transmart database

### ISSUE THREAD

**Issue by gijskant** [thehyve/glowing-bear-docker#1]
- [x] Create Liquibase scripts to generate minimal i2b2demodata and i2b2metadata schemas and data for TranSMART
- [x] Test if the TranSMART API works with those minimal schemas

**Comment by phozzy** [comment]
Have a CI pipeline for compiling pg_bitcount extensions:
https://gitlab.com/thehyve/pg_bitcount
it is a mirror repository from github repository. (conan branch for gitlab-ci).
It compiles binaries.
Now I need to push them to Conan repository and after that prepare container image.

**Comment by phozzy** [comment]
May be there is a sense in dividing this ticket in 2?
point 1&2 to to one ticket related to liquibase, and point 3&4 to an other one, related to pg extensions.
Since anyway we trigger liquibase from Transmart.
And it looks like if we are almost done with liquibase.
@gijskant ?

**Comment by gijskant** [comment]
I agree, will you split it?

**Comment by phozzy** [comment]
@gijskant so now it looks like if this issue can be closed, right?

**Comment by gijskant** [comment]
Docker file and docker-compose file for transmart-api-server and a postgresql database with Liquibase updates activated at startup are available at https://github.com/thehyve/transmart-core/tree/dev/docker.
