### ISSUE TITLE
Add views from biomart_user schema to Liquibase scripts

### ISSUE THREAD

**Issue by gijskant** [thehyve/glowing-bear-docker#12]
Add bitset views for better performance on large datasets.

**Comment by gijskant** [comment]
Depends on #23.

**Comment by gijskant** [comment]
Addressed by https://github.com/thehyve/transmart-core/pull/436. Will be available in upcoming 17.1-HYVE-6 release.

**Comment by ewelinajozwik** [comment]
Resolved in release 17.1-HYVE-6.1, can it be closed now?
