### ISSUE TITLE
Create Docker image for Glowing Bear backend

### ISSUE THREAD

**Issue by gijskant** [thehyve/glowing-bear-docker#2]
- [x] Create Dockerfile for the gb-backend application (using the jar file from Nexus)
- [x] Create a docker-compose script to combine the PostgreSQL database and Glowing Bear backend application
- [x] Publish `glowing-bear-backend` images to Docker Hub

**Comment by ewelinajozwik** [comment]
PR: https://github.com/thehyve/gb-backend/pull/25
