### ISSUE TITLE
Database not set up correctly

### ISSUE THREAD

**Issue by tgymnich** [thehyve/glowing-bear-docker#21]
When I run docker-compose up the TranSMART database does not seem to get initialized properly.

All of the schemas and roles are missing.

<img width="289" alt="Screen Shot 2019-06-01 at 23 16 36" src="https://user-images.githubusercontent.com/7985149/58753673-62a54c00-84c3-11e9-8bb9-207b80390f7f.png">

Am I missing something or are the liquibase scripts not working correctly?

**Comment by gijskant** [comment]
I indeed notice something is wrong, do you see the following error message in your console at startup?
```
transmart-database         | 2019-06-12 15:34:16.705 UTC [52] ERROR:  relation "public.databasechangeloglock" does not exist at character 22                                                                                 
transmart-database         | 2019-06-12 15:34:16.705 UTC [52] STATEMENT:  SELECT COUNT(*) FROM public.databasechangeloglock                                                                                                  
```

**Comment by gijskant** [comment]
However, even with this error, I still get `i2b2demodata` and `i2b2metadata` schemas with all tables. Could you try with a clean volume? `docker container rm transmart-database; docker volume rm docker volume rm glowing-bear-docker_transmart-db-data`

**Comment by tgymnich** [comment]
After running `docker container rm transmart-database; docker volume rm docker volume rm glowing-bear-docker_transmart-db-data` I still don't get `i2b2demodata` and `i2b2metadata`.

I also see the same errors you mentioned above.

**Comment by gijskant** [comment]
It could be that you IDE is misleading. Could you verify with `psql -h localhost -p 9432 -d transmart -U biomart_user -c "select * from pg_schemas"` that the other schemas are really not created? If they appear there, you could use `Database Tools -> Manage Shown Schemas` to display all schemas instead of only the current (public). Hopefully that helps you further...

**Comment by tgymnich** [comment]
You were right the IDE was hiding some of the schemas. 
<img width="290" alt="Screen Shot 2019-06-13 at 10 21 00" src="https://user-images.githubusercontent.com/7985149/59416112-08f72880-8dc5-11e9-835f-21380e8867ce.png">

**Comment by gijskant** [comment]
Great, good luck with trying it out!
