### ISSUE TITLE
Create Docker image for TranSMART API server

### ISSUE THREAD

**Issue by gijskant** [thehyve/glowing-bear-docker#3]
- [x] Create Dockerfile for the TranSMART API server
- [x] Configure logging to stdout
- [x] Create a docker-compose script to combine transmart-database with transmart-api-server
- [ ] Publish images to repository

**Comment by lukaszimmermann** [comment]
Addressed in:
https://github.com/thehyve/transmart-core/pull/408

@gijskant  If you want, I can set the build configuration on Docker Hub if you grant me permissions on the `thehyve/transmart-api-server` repository.
