### ISSUE TITLE
Update Transmart Packer to persist jobs between restarts

### ISSUE THREAD

**Issue by gijskant** [thehyve/glowing-bear-docker#4]
Transmart Packer uses Redis to store information about export jobs. Job information is lost between restarts of Redis.

Acceptance criteria:
- Job information is persisted between restarts of Redis

**Comment by ewelinajozwik** [comment]
@gijskant I checked the docker-compose for transmart-packer and it is already configured to use `append only file` persistence option for redis, there is also a volume for redis image added. I tested it and indeed, export jobs are persisted, so we can consider this task done. 

Other think is that I noticed both python webapp and celery worker images have volumes to store logs and some other tmp app files. This is something  we want to get rid of, right? We can either create a separate task to change logging part and volumes, or just redefine this task.
