### ISSUE TITLE
Issues setting up a local instance

### ISSUE THREAD

**Issue by j-frei** [thehyve/glowing-bear-docker#43]
I have issues to get the instance of transmart/glowingbear running locally on my system.

My .env file looks like this:
```
INSTANCE_ID=DWH1

KEYCLOAK_SERVER_URL=https://keycloak
KEYCLOAK_REALM=transmart
KEYCLOAK_CLIENT_ID=transmart-client
DENY_ACCESS_WITHOUT_ROLE=false

KEYCLOAK_HOSTNAME=keycloak
KEYCLOAK_PASSWORD=12wsq59SYR
KEYCLOAK_USER=admin

GLOWINGBEAR_HOSTNAME=glowingbear
```

Without any modifications, I cannot connect to any keycloak/glowingbear through nginx.

After I added 'network_mode: "host"' to the glowingbear-ssl-proxy, I could connect to glowingbear, keycloak. But after entering https://glowingbear/ and signing in into keycloak/transmart-client, the page states "There is an error connecting to the server.", yielding a 504 error while connecting to https://glowingbear/api/transmart-api-server/health (internally done by the browser, dev tools).

I followed the instructions on the README page. The entries for extra_hosts were added to the docker-compose file. The variant store connector was not used.

**Comment by j-frei** [comment]
I changed some lines in the docker-compose files as documented in the following file.[glowingbear_networkpatch.txt](https://github.com/thehyve/glowing-bear-docker/files/3863741/glowingbear_networkpatch.txt)

Now it works. However, I am not sure whether this is the right solution.

**Comment by ewelinajozwik** [comment]
Hi @j-frei!

The docker-compose files should not require any changes other than described in the README. Here is a shorter description, focused on a local development only: https://gist.github.com/gijskant/79c814470470a12d6b196722b13dfddc

Please make sure that you followed all the steps from this description, especially that `keycloak` and `glowingbear` entries are added to `/etc/hosts` file on your local machine.

I also have some additional questions: 
- what operating system do you use?
- did you check docker logs, when the issue was still there? Were there any errors there (especially from `transmart-api-server` service)? 

Best regards,
Ewelina

**Comment by j-frei** [comment]
Hi Ewelina,

thank you for your answer.

I tried to follow the instructions as close as possible. Although I have to admit that I felt a bit lost in the section about "Setting up Keycloak", especially at "Configure a realm". Your description page does not mention anything related to stuff like importing a realm. 

I guess the realm import is already included in the docker container during startup.

The hosts file was modified according to the instructions.

I am using Fedora 31 with the official docker build from the docker repository. However, I also tried it on an Ubuntu 18.04 instance.
The logs are not here anymore since I have cleaned up all the old files. But without any modification, the logs of _DWH1-transmart-api-server_ showed that the container couldn't connect to the keycloak instance via _DWH1-glowingbear-ssl-proxy_ (No route to host error). I guess this is caused by the network isolation between different docker containers. The modifications I added to the docker-compose files remove these strict isolations. However, I feel like this is absolutely not intended by the developer.

Kind regards,
Johann

**Comment by ewelinajozwik** [comment]
Indeed, when running the docker-compose including Keycloak (e.g. using ./startall), the realm import is done automatically. Looks like this part of our documentation is a bit outdated. Thanks for the comment on this, we are still working on the documentation improvements, so we will try to make this part less confusing. 
Currently the only required change to setup Keycloak is adding application users.

We have not experienced such an issue before, so I am not sure yet what can be the cause. It might be that the `extra_hosts` addition (described in [point 2 of "Running the docker-compose scripts locally" section]( https://github.com/thehyve/glowing-bear-docker#running-the-docker-compose-scripts-locally)) may be different than `172.17.0.1` in your local network configuration. Please check your docker host IP to be sure.

Best,
Ewelina

**Comment by j-frei** [comment]
Hi Ewelina,

the docker IP was correct. However, on Ubuntu 18.04 as well as on my Fedora 31 setup, docker containers cannot access the 172.17.0.1 address. After turning off the firewall, the communication works correctly even without my modifications.

See:
[https://forums.docker.com/t/no-route-to-host-network-request-from-container-to-host-ip-port-published-from-other-container/39063/4](https://forums.docker.com/t/no-route-to-host-network-request-from-container-to-host-ip-port-published-from-other-container/39063/4)

Sorry for the unnecessary confusion and thank you for your support!

Kind regards,
Johann

**Comment by ewelinajozwik** [comment]
Thanks for the update and great that you solved this! I will make sure we include the information about possible firewall problem in the documentation! 

Best regards,
Ewelina
