### ISSUE TITLE
Create a Glowing Bear image serving the application and a backend proxy

### ISSUE THREAD

**Issue by gijskant** [thehyve/glowing-bear-docker#5]
- [x] Update Glowing Bear and its configuration to allow discovery of the hostname and support relative URLs for backend APIs
- [x] Create a Dockerfile that serves Glowing Bear and provides a proxy for backend components using nginx
- [x] Create a docker-compose script that combines transmart-api-server, glowing-bear-backend, transmart-packer and glowing-bear
- [x] To be determined: configuration of SSL certificates (Let's Encrypt, certificates mounted as volumes, generate self-signed certificates)
- [x] Publish glowing-bear image to repository

**Comment by ewelinajozwik** [comment]
PR: https://github.com/thehyve/glowing-bear/pull/576

**Comment by ewelinajozwik** [comment]
Currently certificates are required and are mounted using volumes (they are not auto-generated, have to be provided)
